awsprofile with optional KUBECONFIG
Before, kubectl would issue warnings on every prompt because of PS1,
which uses kubectl to get the context, when KUBECONFIG was set.

Now only a single warning is issued when awsprofile is run.

diff --git a/bash/bash/awsprofile b/bash/bash/awsprofile
--- a/bash/bash/awsprofile
+++ b/bash/bash/awsprofile
@@ -12,6 +12,7 @@ awsprofile() {
   else
     profile=$(_list_awsprofiles | fzf)
   fi
+
   if [[ $profile == 'None' ]]; then
       echo "unsetting AWS_PROFILE and KUBECONFIG" >&2
       unset AWS_PROFILE
@@ -19,7 +20,16 @@ awsprofile() {
       return
   fi
   local env=$(echo $profile | cut -d_ -f2)
-  export AWS_PROFILE=$profile KUBECONFIG=~/.kube/${profile}.yml
+
+  export AWS_PROFILE=$profile
+
+  local kubeconfig=~/.kube/${profile}.yml
+  if [[ -f $kubeconfig ]]; then
+    export KUBECONFIG=$kubeconfig
+  else
+    echo "WARNING: KUBECONFIG not found: $kubeconfig" >&2
+  fi
+
   [[ -f .terraform/environment ]] \
     && [[ $(< .terraform/environment) != $env ]] \
     && terraform workspace select $env \
